# Generated by Django 3.2.4 on 2021-07-02 01:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('brandname', models.CharField(max_length=255)),
                ('stylename', models.CharField(max_length=255, null=True)),
                ('imagepath', models.CharField(max_length=255, null=True)),
                ('retailprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('numberofsale', models.IntegerField(default=0)),
                ('averagesaleprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stylecode', models.CharField(max_length=255, null=True)),
                ('colorway', models.CharField(max_length=255, null=True)),
                ('ticker', models.CharField(max_length=255, null=True)),
                ('releasedate', models.DateTimeField()),
            ],
        ),
    ]
