# Generated by Django 3.2.4 on 2021-07-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='releasedate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='retailprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
