# Generated by Django 3.2.4 on 2021-07-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0002_auto_20210701_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='averagesaleprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
