# Generated by Django 3.2.5 on 2021-07-12 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0006_auto_20210712_0326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trades',
        ),
    ]
