# Generated by Django 3.2.5 on 2021-07-12 04:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0007_delete_trades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('trade_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trade_name', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=255)),
                ('trade_date', models.DateTimeField()),
                ('trade_time', models.CharField(max_length=255)),
                ('trade_size', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('trade_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
