# Generated by Django 3.2.5 on 2021-07-12 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0008_trades'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
