# Generated by Django 3.2.5 on 2021-07-12 04:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0009_delete_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('brand_name', models.CharField(max_length=255)),
                ('style_name', models.CharField(max_length=255, null=True)),
                ('image_path', models.CharField(max_length=255, null=True)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('number_of_sale', models.IntegerField(default=0)),
                ('averge_sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('style_code', models.CharField(max_length=255, null=True)),
                ('colorway', models.CharField(max_length=255, null=True)),
                ('ticker', models.CharField(max_length=255, null=True)),
                ('release_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
