# Generated by Django 3.2.5 on 2021-07-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0010_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='trade_size',
            field=models.CharField(max_length=255),
        ),
    ]
