# Generated by Django 3.2.4 on 2021-07-24 03:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0012_auto_20210712_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayTrades',
            fields=[
                ('ebay_trade_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ebay_trade_name', models.CharField(max_length=255)),
                ('seller', models.CharField(max_length=255)),
                ('sold_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ship_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('size', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sold_date', models.DateTimeField()),
                ('condition', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='averge_sale_price',
            new_name='average_sale_price',
        ),
    ]
