# Generated by Django 3.2.4 on 2021-08-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0015_auto_20210729_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='average_sales_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='number_sales_12_months',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='number_sales_72_hours',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='price_premium',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
