# Generated by Django 3.2.4 on 2021-08-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0016_auto_20210813_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='model_name',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
