# Generated by Django 3.2.4 on 2021-08-26 22:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0017_detail_model_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='image_path',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='model_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='brand_name',
            new_name='urlKey',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='average_sales_price',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='number_sales_12_months',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='number_sales_72_hours',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='price_premium',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='retail_price',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='style_code',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='style_name',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='ticker',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='url',
        ),
        migrations.AddField(
            model_name='detail',
            name='belowRetail',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='imageUrl',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='marketAnnualHigh',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='marketAnnualLow',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='marketHighestBid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='marketHighestBidSize',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='marketLowestAsk',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='marketLowestAskSize',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='marketSalesLast72Hours',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='productId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='detail',
            name='releaseDate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='retailPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='shoe',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='styleId',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='thumbUrl',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='tickerSymbol',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
