# Generated by Django 3.2.4 on 2021-08-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0018_auto_20210826_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='belowRetail',
            new_name='below_retail',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='marketAnnualHigh',
            new_name='market_annual_high',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='marketAnnualLow',
            new_name='market_annual_low',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='marketHighestBid',
            new_name='market_highest_bid',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='marketHighestBidSize',
            new_name='market_highest_bid_size',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='marketLowestAsk',
            new_name='market_lowest_ask',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='marketLowestAskSize',
            new_name='market_lowest_ask_size',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='marketSalesLast72Hours',
            new_name='market_sales_last_72hours',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='productId',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='releaseDate',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='retailPrice',
            new_name='retail_price',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='styleId',
            new_name='style_id',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='thumbUrl',
            new_name='thumb_url',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='tickerSymbol',
            new_name='ticker_symbol',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='urlKey',
            new_name='url_key',
        ),
    ]
