# Generated by Django 3.2.4 on 2021-08-29 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0019_auto_20210827_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockxAnalyze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyze_target_date', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('average_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('high_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('low_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('number_of_trades', models.IntegerField()),
                ('publish_date', models.CharField(max_length=255)),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sneakers.detail')),
            ],
        ),
        migrations.DeleteModel(
            name='Trades',
        ),
    ]
