# Generated by Django 3.2.4 on 2021-08-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0020_auto_20210829_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockxanalyze',
            name='average_price',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stockxanalyze',
            name='high_price',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stockxanalyze',
            name='low_price',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
