# Generated by Django 3.2.4 on 2021-08-30 05:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0022_alter_stockxanalyze_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockxanalyze',
            name='id',
        ),
        migrations.AddField(
            model_name='stockxanalyze',
            name='sneaka_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
