# Generated by Django 3.2.4 on 2021-08-30 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0026_rename_id_stockx_analyze_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stockx',
        ),
    ]
